kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: devops-cluster-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: devops-cluster-full-access
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: {{APPDEVOPS_OBJECTID}}