kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user-access
  namespace: myapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: user-full-access
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  namespace: myapp
  name: {{APPDEV_OBJECTID}}